MVCFitnessApp/Controllers/MemberController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MVCFitnessApp.Models;
using MVCFitnessApp.ViewModels;
using System.Data.Entity.Infrastructure;
using System.IO;

namespace MVCFitnessApp.Controllers
{
    public class MemberController : Controller
    {
        private Factory db = new Factory();

        // GET: Member
        public ActionResult Index(int? id, int? activityID, string searchString)
        {
            var viewModel = new MemberIndexData();
            viewModel.Members = db.Members
                .OrderBy(m => m.LastName);

            if (id != null)
            {           
                ViewBag.MemberID = id.Value;
                viewModel.Activities = viewModel.Members.Where(
                    m => m.MemberID == id.Value).Single().Activities;
            }

            return View(viewModel);
        }

        // GET: Member/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Member member = db.Members.Include(m => m.FilePathMembers).SingleOrDefault(m => m.MemberID == id);

            if (member == null)
            {
                return HttpNotFound();
            }
            return View(member);
        }

        // GET: Member/Create
        [Authorize(Roles = "Coach, Administrator")]
        public ActionResult Create()
        {
            var member = new Member();
            member.Activities = new List<Activity>();
            PopulateAssignedActivityData(member);
            return View();
        }

        // POST: Member/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Coach, Administrator")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MemberID,LastName,FirstName,EnrollmentDate")] Member member, string[] selectedActivities, HttpPostedFileBase upload)
        {
            if (selectedActivities != null)
            {
                member.Activities = new List<Activity>();
                foreach (var activity in selectedActivities)
                {
                    var activityToAdd = db.Activities.Find(int.Parse(activity));
                    member.Activities.Add(activityToAdd);
                }
            }
            if (ModelState.IsValid)
            {
                if (upload != null && upload.ContentLength > 0)
                {
                    var photo = new FilePathMember
                    {
                        FileName = Path.GetFileName(upload.FileName),
                        FileType = "Photo"
                    };

                    string path = Path.Combine(Server.MapPath("~/Pics/Member/"), Path.GetFileName(upload.FileName));

                    upload.SaveAs(path);
                    member.FilePathMembers = new List<FilePathMember>();
                    member.FilePathMembers.Add(photo);
                }

                db.Members.Add(member);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            PopulateAssignedActivityData(member);
            return View(member);
        }

        // GET: Member/Edit/5
        [Authorize(Roles = "User, Coach, Administrator")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            
            Member member = db.Members
                .Include(m => m.Activities)
                .Where(m => m.MemberID == id)
                .Single();

            PopulateAssignedActivityData(member);

            if (member == null)
            {
                return HttpNotFound();
            }
            return View(member);
        }

        // POST: Member/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "User, Coach, Administrator")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int? id, string[] selectedActivities, HttpPostedFileBase upload)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var memberToUpdate = db.Members
               .Include(m => m.Activities)
               .Where(m => m.MemberID == id)
               .Include(m => m.FilePathMembers)
               .Single();

            if (TryUpdateModel(memberToUpdate, "",
               new string[] { "LastName", "FirstName", "EnrollmentDate" }))
            {
                try
                {
                    if (upload != null && upload.ContentLength > 0)
                    {
                        if (memberToUpdate.FilePathMembers.Any(f => f.FileType == "Photo"))
                        {
                            db.FilePathMembers.Remove(memberToUpdate.FilePathMembers.First(f => f.FileType == "Photo"));
                        }

                        var photo = new FilePathMember
                        {
                            FileName = Path.GetFileName(upload.FileName),
                            FileType = "Photo",
                        };

                        string path = Path.Combine(Server.MapPath("~/Pics/Member/"), Path.GetFileName(upload.FileName));

                        upload.SaveAs(path);
                        memberToUpdate.FilePathMembers = new List<FilePathMember> { photo };
                    }

                    UpdateMemberActivities(selectedActivities, memberToUpdate);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                catch (RetryLimitExceededException /* dex */)
                {
                    //Log the error (uncomment dex variable name and add a line here to write a log.
                    ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists, see your system administrator.");
                }
            }
            PopulateAssignedActivityData(memberToUpdate);
            return View(memberToUpdate);
        }

        private void UpdateMemberActivities(string[] selectedActivities, Member memberToUpdate)
        {
            if (selectedActivities == null)
            {
                memberToUpdate.Activities = new List<Activity>();
                return;
            }

            var selectedActivitiesHS = new HashSet<string>(selectedActivities);
            var memberActivities = new HashSet<int>
                (memberToUpdate.Activities.Select(m => m.ActivityID));

            foreach (var activity in db.Activities)
            {
                if (selectedActivitiesHS.Contains(activity.ActivityID.ToString()))
                {
                    if (!memberActivities.Contains(activity.ActivityID))
                    {
                        memberToUpdate.Activities.Add(activity);
                    }
                }
                else
                {
                    if (memberActivities.Contains(activity.ActivityID))
                    {
                        memberToUpdate.Activities.Remove(activity);
                    }
                }
            }
        }

        // GET: Member/Delete/5
        [Authorize(Roles = "Coach, Administrator")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Member member = db.Members.Include(m => m.FilePathMembers).SingleOrDefault(m => m.MemberID == id);

            if (member == null)
            {
                return HttpNotFound();
            }
            return View(member);
        }

        // POST: Member/Delete/5
        [Authorize(Roles = "Coach, Administrator")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Member member = db.Members
                .Where(m => m.MemberID == id)
                .Single();

            db.Members.Remove(member);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        private void PopulateAssignedActivityData(Member member)
        {
            var allActivities = db.Activities;
            var memberActivities = new HashSet<int>(member.Activities.Select(e => e.ActivityID));
            var viewModel = new List<AssignedActivityData>();

            foreach (var activity in allActivities)
            {
                //viewmodel to get ActivityID and Name from Activity
                viewModel.Add(new AssignedActivityData
                {
                    ActivityID = activity.ActivityID,
                    Name = activity.Name,
                    Assigned = memberActivities.Contains(activity.ActivityID)
                });
            }
            ViewBag.Activities = viewModel;
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MVCFitnessApp/Controllers/MembersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MVCFitnessApp.Models;
using PagedList;

namespace MVCFitnessApp.Controllers
{
    public class MembersController : Controller
    {
        private Factory db = new Factory();

        public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.LastNameSortParm = String.IsNullOrEmpty(sortOrder) ? "lastname_desc" : "";
            ViewBag.FirstNameSortParm = String.IsNullOrEmpty(sortOrder) ? "firstname_desc" : "";
            ViewBag.DateSortParm = sortOrder == "Date" ? "date_desc" : "Date";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            var members = from s in db.Members
                           select s;
            if (!String.IsNullOrEmpty(searchString))
            {
                members = members.Where(s => s.LastName.Contains(searchString)
                                       || s.FirstName.Contains(searchString));
            }
            switch (sortOrder)
            {
                case "lastname_desc":
                    members = members.OrderByDescending(s => s.LastName);
                    break;
                case "firstname_desc":
                    members = members.OrderByDescending(s => s.FirstName);
                    break;
                case "Date":
                    members = members.OrderBy(s => s.EnrollmentDate);
                    break;
                case "date_desc":
                    members = members.OrderByDescending(s => s.EnrollmentDate);
                    break;
                default:
                    members = members.OrderBy(s => s.LastName);
                    break;
            }
            int pageSize = 6;
            int pageNumber = (page ?? 1);
            return View(members.ToPagedList(pageNumber, pageSize));
        }

        // GET: Members/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Member member = db.Members.Find(id);
            if (member == null)
            {
                return HttpNotFound();
            }
            return View(member);
        }

        // GET: Members/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Members/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MemberID,LastName,FirstName,EnrollmentDate")] Member member)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.Members.Add(member);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch (DataException /* dex */)
            {
                //Log the error (uncomment dex variable name and add a line here to write a log.
                ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists see your system administrator.");
            }
            return View(member);
        }

        // GET: Members/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Member member = db.Members.Find(id);
            if (member == null)
            {
                return HttpNotFound();
            }
            return View(member);
        }

        //[HttpPost, ActionName("Edit")]
        //[ValidateAntiForgeryToken]
        //public ActionResult EditPost(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    var memberToUpdate = db.Members.Find(id);
        //    if (TryUpdateModel(memberToUpdate, "",
        //       new string[] { "MemberID", "LastName", "FirstName", "EnrollmentDate" }))
        //    {
        //        try
        //        {
        //            db.SaveChanges();

        //            return RedirectToAction("Index");
        //        }
        //        catch (DataException /* dex */)
        //        {
        //            //Log the error (uncomment dex variable name and add a line here to write a log.
        //            ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists, see your system administrator.");
        //        }
        //    }
        //    return View(memberToUpdate);
        //}

        // POST: Members/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MemberID,LastName,FirstName,EnrollmentDate")] Member member)
        {
            if (ModelState.IsValid)
            {
                db.Entry(member).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(member);
        }

        // GET: Members/Delete/5
        public ActionResult Delete(int? id, bool? saveChangesError = false)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            if (saveChangesError.GetValueOrDefault())
            {
                ViewBag.ErrorMessage = "Delete failed. Try again, and if the problem persists see your system administrator.";
            }
            Member member = db.Members.Find(id);
            if (member == null)
            {
                return HttpNotFound();
            }
            return View(member);
        }

        // POST: Members/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                Member member = db.Members.Find(id);
                db.Members.Remove(member);
                db.SaveChanges();
            }
            catch (DataException/* dex */)
            {
                //Log the error (uncomment dex variable name and add a line here to write a log.
                return RedirectToAction("Delete", new { id = id, saveChangesError = true });
            }
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MVCFitnessApp/Views/Member/Create.cshtml
@model MVCFitnessApp.Models.Member

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Member", null, FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Member</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EnrollmentDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EnrollmentDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EnrollmentDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Photo", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" id="Photo" name="upload" />
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Signed Up", new { @class = "control-label col-md-2" })
            <div class="col-md-offset-2 col-md-10">
                <table>
                    <tr>
                        @{
                            int cnt = 0;
                            List<MVCFitnessApp.ViewModels.AssignedActivityData> activities = ViewBag.Activities;

                            foreach (var activity in activities)
                            {
                                if (cnt++ % 3 == 0)
                                {
                                    @:</tr><tr>
                                }
                                @:<td>
                                    <input type="checkbox"
                                           name="selectedActivities"
                                           value="@activity.ActivityID"
                                           @(Html.Raw(activity.Assigned ? "checked=\"checked\"" : "")) />
                                        @activity.Name
                                        @:</td>
                               }
                            @:</tr>
                        }
                    </table>
                </div>
            </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MVCFitnessApp/Views/Member/Delete.cshtml
@model MVCFitnessApp.Models.Member

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Member</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EnrollmentDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EnrollmentDate)
        </dd>

        @if (Model.FilePathMembers.Any(f => f.FileType == "Photo"))
        {
            <dt>
                Photo
            </dt>
            <dd>
                <img src="~/pics/Member/@Model.FilePathMembers.First(f => f.FileType == "Photo").FileName" alt="Member Photo" />
            </dd>
        }

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

MVCFitnessApp/Views/Member/Details.cshtml
@model MVCFitnessApp.Models.Member

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Member</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EnrollmentDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EnrollmentDate)
        </dd>

        @if (Model.FilePathMembers.Any(f => f.FileType == "Photo"))
        {
            <dt>
                Photo
            </dt>
            <dd>
                <img src="~/pics/Member/@Model.FilePathMembers.First(f => f.FileType == "Photo").FileName" alt="Member Photo" />
            </dd>
        }

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.MemberID }, new { @class = "btn btn-success" }) |
    @Html.ActionLink("Back to List", "Index")
</p>

MVCFitnessApp/Views/Member/Edit.cshtml
@model MVCFitnessApp.Models.Member

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit", "Member", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Member</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MemberID)

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EnrollmentDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EnrollmentDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EnrollmentDate, "", new { @class = "text-danger" })
            </div>
        </div>

        @if (Model.FilePathMembers.Any(f => f.FileType == "Photo"))
        {
            <div class="form-group">
                <span class="control-label col-md-2"><strong>Current Photo</strong></span>
                <div class="col-md-10">
                    <img src="~/pics/Member/@Model.FilePathMembers.First(f => f.FileType == "Photo").FileName" alt="Member Photo" />
                </div>
            </div>
        }

        <div class="form-group">
            @Html.Label("Change Photo", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" id="MemberPhoto" name="upload" />
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Enrollments", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <table>
                    <tr>
                        @{
                            int cnt = 0;
                            List<MVCFitnessApp.ViewModels.AssignedActivityData> activities = ViewBag.Activities;
                            foreach (var enrollment in activities)
                            {
                                if (cnt++ % 3 == 0)
                                {
                                    @:</tr><tr>
                                }
                                @:<td>
                                    <input type="checkbox"
                                           name="selectedActivities"
                                           value="@enrollment.ActivityID"
                                           @(Html.Raw(enrollment.Assigned ? "checked=\"checked\"" : "")) />
                                    @enrollment.Name
                                    @:</td>
                                }
                            @:</tr>
                        }
                    </table>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-success" />
                </div>
            </div>
        </div>
                            }

                        <div>
                            @Html.ActionLink("Back to List", "Index")
                        </div>

                        @section Scripts {
                            @Scripts.Render("~/bundles/jqueryval")
                        }

MVCFitnessApp/Views/Member/Index.cshtml
@model MVCFitnessApp.ViewModels.MemberIndexData

@{
    ViewBag.Title = "Members";
}

<h2>Members</h2>
<hr />
<div class="row">
    <div class="col-md-12">
        <h3>Create new Member</h3>
        @Html.ActionLink("Create", "Create", null, new { @class = "btn btn-primary" })
        <hr />
    </div>
</div>

<table class="table table-striped table-bordered">
    <tr>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Enrollment Date</th>
        <th></th>
    </tr>

    @foreach (var item in Model.Members)
    {
        string selectedRow = "";
        if (item.MemberID == ViewBag.MemberID)
        {
            selectedRow = "success";
        }
        <tr class="@selectedRow">
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EnrollmentDate)
            </td>

            <td>
                @Html.ActionLink("Select", "Index", new { id = item.MemberID }, new { @class = "btn btn-default" }) 
                @Html.ActionLink("Edit", "Edit", new { id = item.MemberID }, new { @class = "btn btn-success" }) 
                @Html.ActionLink("Details", "Details", new { id = item.MemberID }, new { @class = "btn btn-info" }) 
                @Html.ActionLink("Delete", "Delete", new { id = item.MemberID }, new { @class = "btn btn-danger" })
            </td>
        </tr>
    }

</table>

@if (Model.Activities != null)
{
    <h3>Activity Enrollments</h3>
    <table class="table table-striped table-bordered">
        <tr>
            <th>Title</th>
            <th>Description</th>
        </tr>

            @foreach (var item in Model.Activities)
            {
                string selectedRow = "";
                if (item.ActivityID == ViewBag.ActivityID)
                {
                    selectedRow = "success";
                }
                <tr class="@selectedRow">
                    
                    <tr>
                        <td>
                            @item.Name
                        </td>
                        <td>
                            @item.Description
                        </td>
                    </tr>
                </tr>          
            }
    </table>
}