MVCFitnessApp/Models/Coach.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace MVCFitnessApp.Models
{
    public class Coach
    {
        [Display(Name = "Number")]
        public int CoachID { get; set; }

        [Required]
        [Column("FirstName")]
        [Display(Name = "First Name")]
        [StringLength(50)]
        public string FirstName { get; set; }

        [Required]
        [Display(Name = "Last Name")]
        [StringLength(50)]
        public string LastName { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        [Display(Name = "Hire Date")]
        public DateTime HireDate { get; set; }

        [Display(Name = "Full Name")]
        public string FullName
        {
            get { return FirstName + " " + LastName; }
        }

        //Navigation properties. Holds entities (more than 1) related to a given entity.
        public virtual ICollection<Activity> Activities { get; set; }
        public virtual ICollection<FilePath> FilePaths { get; set; }
    }
}

MVCFitnessApp/Controllers/CoachController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MVCFitnessApp.Models;
using MVCFitnessApp.ViewModels;
using System.Data.Entity.Infrastructure;
using System.IO;

namespace MVCFitnessApp.Controllers
{
    public class CoachController : Controller
    {
        private Factory db = new Factory();

        // GET: Coach
        public ActionResult Index(int? id, int? activityID)
        {
            var viewModel = new CoachIndexData();
            viewModel.Coachs = db.Coachs
                .Include(c => c.Activities.Select(m => m.Members))
                .OrderBy(c => c.LastName);

            if (id != null)
            {
                ViewBag.CoachID = id.Value;
                viewModel.Activities = viewModel.Coachs.Where(
                    c => c.CoachID == id.Value).Single().Activities;
            }

            if (activityID != null)
            {
                ViewBag.ActivityID = activityID.Value;
                //// Lazy loading 
                //viewModel.Activities = viewModel.Members.Where(
                //    m => m.MemberID == id.Value).Single().Activities;

                // Explicit loading 
                var selectedActivity = viewModel.Activities.Where(x => x.ActivityID == activityID).Single();
                db.Entry(selectedActivity).Collection(x => x.Members).Load();

                foreach (Member member in selectedActivity.Members)
                {
                    db.Entry(member).Collection(x => x.Activities).Load();
                }

                viewModel.Members = selectedActivity.Members;
            }

            return View(viewModel);
        }

        // GET: Coach/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Coach coach = db.Coachs.Include(c => c.FilePaths).SingleOrDefault(c => c.CoachID == id);

            if (coach == null)
            {
                return HttpNotFound();
            }
            return View(coach);
        }

        // GET: Coach/Create
        [Authorize(Roles = "Coach, Administrator")]
        public ActionResult Create()
        {
            var coach = new Coach();
            coach.Activities = new List<Activity>();
            PopulateAssignedActivityData(coach);
            return View();
        }

        // POST: Coach/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Coach, Administrator")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CoachID,LastName,FirstName,HireDate")] Coach coach, string[] selectedActivities, HttpPostedFileBase upload)
        {
            if (selectedActivities != null)
            {
                coach.Activities = new List<Activity>();
                foreach (var activity in selectedActivities)
                {
                    var activityToAdd = db.Activities.Find(int.Parse(activity));
                    coach.Activities.Add(activityToAdd);
                }
            }
            if (ModelState.IsValid)
            {
                if (upload != null && upload.ContentLength > 0)
                {
                    var photo = new FilePath
                    {
                        FileName = Path.GetFileName(upload.FileName),
                        FileType = "Photo"
                    };

                    string path = Path.Combine(Server.MapPath("~/Pics/Coach/"), Path.GetFileName(upload.FileName));

                    upload.SaveAs(path);
                    coach.FilePaths = new List<FilePath>();
                    coach.FilePaths.Add(photo);
                }

                db.Coachs.Add(coach);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            PopulateAssignedActivityData(coach);
            return View(coach);
        }

        // GET: Coach/Edit/5
        [Authorize(Roles = "Coach, Administrator")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Coach coach = db.Coachs
                .Include(a => a.Activities)
                .Where(a => a.CoachID == id)
                .Single();

            PopulateAssignedActivityData(coach);

            if (coach == null)
            {
                return HttpNotFound();
            }
            return View(coach);
        }

        private void PopulateAssignedActivityData(Coach coach)
        {
            var allActivities = db.Activities;
            var CoachActivities = new HashSet<int>(coach.Activities.Select(c => c.ActivityID));
            var viewModel = new List<AssignedActivityData>();

            foreach (var activity in allActivities)
            {
                //viewmodel to get ActivityID and Name from Activity
                viewModel.Add(new AssignedActivityData
                {
                    ActivityID = activity.ActivityID,
                    Name = activity.Name,
                    Assigned = CoachActivities.Contains(activity.ActivityID)
                });
            }
            ViewBag.Activities = viewModel;
        }

        // POST: Coach/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Coach, Administrator")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int? id, string[] selectedActivities, HttpPostedFileBase upload)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var coachToUpdate = db.Coachs
               .Include(c => c.Activities)
               .Where(c => c.CoachID == id)
               .Include(c => c.FilePaths)            
               .Single();

            if (TryUpdateModel(coachToUpdate, "",
               new string[] { "LastName", "FirstName", "HireDate" }))
            {
                try
                {
                    if (upload != null && upload.ContentLength > 0)
                    {
                        if (coachToUpdate.FilePaths.Any(f => f.FileType == "Photo"))
                        {
                            db.FilePaths.Remove(coachToUpdate.FilePaths.First(f => f.FileType == "Photo"));
                        }

                        var photo = new FilePath
                        {
                            FileName = Path.GetFileName(upload.FileName),
                            //FileName = Path.GetFileName(upload.FileName),
                            FileType = "Photo",
                        };

                        string path = Path.Combine(Server.MapPath("~/Pics/Coach/"), Path.GetFileName(upload.FileName));

                        upload.SaveAs(path);
                        coachToUpdate.FilePaths = new List<FilePath> { photo };
                    }

                    UpdateCoachActivities(selectedActivities, coachToUpdate);

                    db.SaveChanges();

                    return RedirectToAction("Index");
                }
                catch (RetryLimitExceededException /* dex */)
                {
                    //Log the error (uncomment dex variable name and add a line here to write a log.
                    ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists, see your system administrator.");
                }
            }
            PopulateAssignedActivityData(coachToUpdate);
            return View(coachToUpdate);
        }

        private void UpdateCoachActivities(string[] selectedActivities, Coach coachToUpdate)
        {
            if (selectedActivities == null)
            {
                coachToUpdate.Activities = new List<Activity>();
                return;
            }

            var selectedActivitiesHS = new HashSet<string>(selectedActivities);
            var coachActivities = new HashSet<int>
                (coachToUpdate.Activities.Select(c => c.ActivityID));

            foreach (var activity in db.Activities)
            {
                if (selectedActivitiesHS.Contains(activity.ActivityID.ToString()))
                {
                    if (!coachActivities.Contains(activity.ActivityID))
                    {
                        coachToUpdate.Activities.Add(activity);
                    }
                }
                else
                {
                    if (coachActivities.Contains(activity.ActivityID))
                    {
                        coachToUpdate.Activities.Remove(activity);
                    }
                }
            }
        }

        // GET: Coach/Delete/5
        [Authorize(Roles = "Coach, Administrator")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Coach coach = db.Coachs.Include(c => c.FilePaths).SingleOrDefault(c => c.CoachID == id);
            
            if (coach == null)
            {
                return HttpNotFound();
            }
            return View(coach);
        }

        // POST: Coach/Delete/5
        [Authorize(Roles = "Coach, Administrator")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Coach coach = db.Coachs

MVCFitnessApp/Views/Coach/Create.cshtml
@model MVCFitnessApp.Models.Coach

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Coach", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    {
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Coach</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.HireDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HireDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HireDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Photo", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" id="Photo" name="file" />
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Coach on", new { @class = "control-label col-md-2" })
            <div class="col-md-offset-2 col-md-10">
                <table>
                    <tr>
                        @{
                            int cnt = 0;
                            List<MVCFitnessApp.ViewModels.AssignedActivityData> activities = ViewBag.Activities;

                            foreach (var activity in activities)
                            {
                                if (cnt++ % 3 == 0)
                                {
                                    @:</tr><tr>
                                }
                                @:<td>
                                    <input type="checkbox"
                                           name="selectedActivities"
                                           value="@activity.ActivityID"
                                           @(Html.Raw(activity.Assigned ? "checked=\"checked\"" : "")) />
                                    @activity.Name
                                    @:</td>
                               }
                            @:</tr>
                        }
                    </table>
                </div>
            </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-success" />
            </div>
        </div>
    </div>
    }
}


<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MVCFitnessApp/Views/Coach/Delete.cshtml
@model MVCFitnessApp.Models.Coach

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Coach</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HireDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HireDate)
        </dd>

        @if (Model.FilePaths.Any(f => f.FileType == "Photo"))
        {
            <dt>
                Photo
            </dt>
            <dd>
                <img src="~/pics/Coach/@Model.FilePaths.First(f => f.FileType == "Photo").FileName" alt="Coach Photo" />
            </dd>
        }

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

MVCFitnessApp/Views/Coach/Details.cshtml
@model MVCFitnessApp.Models.Coach

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Coach</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HireDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HireDate)
        </dd>

        @if (Model.FilePaths.Any(f => f.FileType == "Photo"))
        {
            <dt>
                Photo
            </dt>
            <dd>
                <img src="~/pics/Coach/@Model.FilePaths.First(f => f.FileType == "Photo").FileName" alt="Coach Photo" />
            </dd>
        }
    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.CoachID }, new { @class = "btn btn-success" }) |
    @Html.ActionLink("Back to List", "Index")
</p>

MVCFitnessApp/Views/Coach/Edit.cshtml
@model MVCFitnessApp.Models.Coach

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit", "Coach", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Coach</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.CoachID)

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HireDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HireDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HireDate, "", new { @class = "text-danger" })
            </div>
        </div>

        @if (Model.FilePaths.Any(f => f.FileType == "Photo"))
        {
            <div class="form-group">
                <span class="control-label col-md-2"><strong>Current Photo</strong></span>
                <div class="col-md-10">
                    <img src="~/pics/Coach/@Model.FilePaths.First(f => f.FileType == "Photo").FileName" alt="Coach Photo" />
                </div>
            </div>
        }

        <div class="form-group">
            @Html.Label("Change Photo", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" id="CoachPhoto" name="upload" />
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Coach on", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <table>
                    <tr>
                        @{
                            int cnt = 0;
                            List<MVCFitnessApp.ViewModels.AssignedActivityData> activities = ViewBag.Activities;

                            foreach (var activity in activities)
                            {
                                if (cnt++ % 3 == 0)
                                {
                                    @:</tr><tr>
                                }
                                @:<td>
                                    <input type="checkbox"
                                           name="selectedActivities"
                                           value="@activity.ActivityID"
                                           @(Html.Raw(activity.Assigned ? "checked=\"checked\"" : "")) />
                                    @activity.Name
                                    @:</td>
                            }
                            @:</tr>
                        }
                    </table>
                </div>
            </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MVCFitnessApp/Views/Coach/Index.cshtml
@model MVCFitnessApp.ViewModels.CoachIndexData

@{
    ViewBag.Title = "Coaches";
}

<h2>Coaches</h2>
<hr />
<div class="row">
    <div class="col-md-12">
        <h3>Create new Coach</h3>
        @Html.ActionLink("Create", "Create", null, new { @class = "btn btn-primary" })
        <hr />
    </div>
</div>

<table class="table table-striped table-bordered">
    <tr>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Hire Date</th>
        <th>Activities</th>
        <th></th>
    </tr>

    @foreach (var item in Model.Coachs)
    {
        string selectedRow = "";
        if (item.CoachID == ViewBag.CoachID)
        {
            selectedRow = "success";
        }
        <tr class="@selectedRow">
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.HireDate)
            </td>
            <td>
                @{
                    foreach (var activity in item.Activities)
                    {
                        @activity.Name <br />
                    }
                }
            </td>

            <td>
                @Html.ActionLink("Select", "Index", new { id = item.CoachID }, new { @class = "btn btn-default" }) 
                @Html.ActionLink("Edit", "Edit", new { id = item.CoachID }, new { @class = "btn btn-success" }) 
                @Html.ActionLink("Details", "Details", new { id = item.CoachID }, new { @class = "btn btn-info" }) 
                @Html.ActionLink("Delete", "Delete", new { id = item.CoachID }, new { @class = "btn btn-danger" })
            </td>
        </tr>
    }

</table>

@if (Model.Activities != null)
{
    <h3>Coach on Activities</h3>
    <table class="table table-striped table-bordered">
        <tr>
            <th></th>
            <th>Number</th>
            <th>Title</th>
            <th>Description</th>
        </tr>

        @foreach (var item in Model.Activities)
        {
            string selectedRow = "";
            if (item.ActivityID == ViewBag.ActivityID)
            {
                selectedRow = "success";
            }
            <tr class="@selectedRow">
                <td>
                    @Html.ActionLink("Select", "Index", new { activityID = item.ActivityID }, new { @class = "btn btn-default" })
                </td>
                <td>
                    @item.ActivityID
                </td>
                <td>
                    @item.Name
                </td>
                <td>
                    @item.Description
                </td>
            </tr>
        }
    </table>
}
@if (Model.Members != null)
{
    <h3>Members Enrolled</h3>
    <table class="table table-striped table-bordered">
        <tr>
            <th>Name</th>
        </tr>
        @foreach (var item in Model.Members)
        {
            <tr>
                <td>
                    @item.FullName
                </td>
            </tr>
        }
    </table>
}