MVCFitnessApp/Models/Sponsor.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Linq;
using System.Web;
using System.Xml.Serialization;

namespace MVCFitnessApp.Models
{
    public class Sponsor
    {
        public Sponsor()
        {
            this.Company = null;
            this.Website = null;
            this.Picture = null;
        }
        
        public Sponsor(int id, string company, string website, string picture)
        {
            this.Id = id;
            this.Company = company;
            this.Website = website;
            this.Picture = picture;
        }
        
        public int Id { get; set; }

        [Required]
        [Display(Name = "Company name")]
        public string Company { get; set; }

        [Required]
        [Display(Name = "Website")]
        public string Website { get; set; }

        [Required]
        [Display(Name = "Logo file")]
        public string Picture { get; set; }

        public HttpPostedFileBase Logo { get; set; }


    }
}

MVCFitnessApp/Controllers/SponsorController.cs
using MVCFitnessApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;

namespace MVCFitnessApp.Controllers
{
    [AllowAnonymous] // Needs to be changed to Administrator
    //[Authorize(Roles ="Administrator")]
    public class SponsorController : Controller
    {
        private SponsorRepo repo = new SponsorRepo();


        // GET: Sponsors
        public ActionResult Index()        // WORKING <-------
        {
            return View(repo.GetSponsors());
        }


        // GET: Sponsor/Details/5
        public ActionResult Details(int id)
        {
            Sponsor sponsor = repo.GetSponsorById(id);
            if(sponsor == null)
            {
                return HttpNotFound();
            }
            return View(sponsor);
        }


        // GET: Sponsor/Create
        public ActionResult Create()        // WORKING <-------
        {
            return View();
        }

        // POST: Sponsor/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Sponsor sponsor)        // WORKING <-------
        {
            if (ModelState.IsValid)
            {
                if (sponsor.Logo != null)
                {
                    sponsor.Logo.SaveAs(HttpContext.Server.MapPath("~/Pics/sponsor/") + sponsor.Logo.FileName);
                }

                var SponserData = new Sponsor()
                {
                    Company = sponsor.Company,
                    Website = sponsor.Website,
                    Picture = sponsor.Logo.FileName
                };

                repo.InsertSponsor(SponserData);
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }

        // GET: Sponsor/Edit/5
        public ActionResult Edit(int id)        // WORKING <-------
        {
            Sponsor sponsor = repo.GetSponsorById(id);
            if (sponsor == null)
            {
                return HttpNotFound();
            }
            return View(sponsor);
        }

        // POST: Sponsor/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Sponsor sponsor)        // WORKING <-------
        {
            try
            {
                // TODO: Add update logic here
                if (ModelState.IsValid)
                {
                    repo.EditSponsor(sponsor);
                    return View(sponsor);
                }

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Sponsor/Delete/5
        public ActionResult Delete(int id)
        {
            // Get the sponsor from repository by id
            Sponsor sponsor = repo.GetSponsorById(id);
            // Check retrieved sponsor object
            if (sponsor == null)
            {
                return HttpNotFound();
            }
            // Return delete view for this sponsor
            return View(sponsor);
        }

        // POST: Sponsor/Delete/5
        [HttpPost]
        public ActionResult Delete(Sponsor sponsor)
        {
            // Delete logic here
            try
            {
                // Get this sponsor id as id
                int id = sponsor.Id;
                // Call the delete method in repository with id as parametre
                repo.DeleteSponsor(id);
                // Then redirect to the sponsor index page
                return RedirectToAction("Index");
            }
            catch
            {
                return View(sponsor);
            }
        }
    }
}

MVCFitnessApp/Views/Sponsor/Create.cshtml
@model MVCFitnessApp.Models.Sponsor

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Sponsor", FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Sponsor</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Company, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Company, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Company, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Website, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Website, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Website, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Picture, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Picture, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Picture, "", new { @class = "text-danger" })
            </div>
        </div>

        @Html.LabelFor(model => model.Logo, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" name="Logo" id="Logo" />
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MVCFitnessApp/Views/Sponsor/Delete.cshtml
@model MVCFitnessApp.Models.Sponsor

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Sponsor</h4>
    <img src="~/images/sponsor/@Html.DisplayFor(model => model.Picture)" alt="logo" />
    <hr />

    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Company)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Company)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Website)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Website)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Picture)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Picture)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            @Html.ActionLink("Back to List", "Index", new { @class = "btn btn-primary" })
        </div>
    }
</div>

MVCFitnessApp/Views/Sponsor/Details.cshtml
@model MVCFitnessApp.Models.Sponsor

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Sponsor</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Company)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Company)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Website)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Website)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Picture)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Picture)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

MVCFitnessApp/Views/Sponsor/Edit.cshtml
@model MVCFitnessApp.Models.Sponsor

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Sponsor</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Company, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Company, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Company, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Website, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Website, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Website, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Picture, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Picture, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Picture, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MVCFitnessApp/Views/Sponsor/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model IEnumerable<MVCFitnessApp.Models.Sponsor>


<h1>Sponsors Index Page</h1>
<hr />
<div class="row">
    <div class="col-md-12">
        <h3>Create new sponsor</h3>
        @Html.ActionLink("Create new sponsor", "Create", null, new { @class = "btn btn-primary" })
        <hr />
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <h3>Our sponsors (from xml)</h3>
        <table class="table table-striped table-bordered">
            <tr>
                <th>Edit</th>
                <th>#</th>
                <th>Company</th>
                <th>Website</th>
                <th>Picture</th>
                <th>Delete</th>
            </tr>
            @foreach (var item in Model)
            {
                <tr>
                    <td>

                        @Html.ActionLink("Edit", "Edit", new { id = item.Id }, new { @class = "btn btn-success" })
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Id)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Company)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Website)
                    </td>
                    <td>
                
                        <img src="~/Pics/sponsor/@Html.DisplayFor(modelItem => item.Picture)" 
                             alt="@Html.DisplayFor(modelItem => item.Company) + logo"
                             style="max-width:70px; max-height:70px;" />
                    </td>
                    <td>
                        @Html.ActionLink("Delete", "Delete", new { id = item.Id }, new { @class = "btn btn-danger" })                       
                        
                    </td>
                </tr>
            }
        </table>  
    </div>
</div>